### ISSUE TITLE
Mudar o cursor do mouse nos botões de `Próxima` e `Anterior` na tela de deputados

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#10]
**Descrição da feature:**
Mudar o cursor do mouse nos botões de `Próxima` e `Anterior`.

**Necessidade:**
Para passar a melhor sensação que os botões são clicáveis.

**Implementação:**
No CSS, você pode adicionar a propriedade `cursor` e mudar o cursor do mouse.

**Comment by objNameGit** [comment]
can I take this task?
What should the cursor look like?

**Comment by ghost** [comment]
Yes. 
The cursor can be the standard
