### ISSUE TITLE
Usar hooks no componentes Partido

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#16]
**Descrição da feature:**
Utilizar hooks no componente de [Partido](https://github.com/Rickecr/CamaraDosDeputados/blob/master/src/Components/Partidos/pagePartido.js).

**Necessidade:**
Bom para organizar o código e o React está focando no uso de hooks.

**Implementação:**
Implementa hooks na tela de partido.

**Comment by ghost** [comment]
Pode se basear no que o @hjJunior fez na tela [Deputado](https://github.com/Rickecr/CamaraDosDeputados/blob/master/src/Components/Deputados/pageDeputado.js)

**Comment by fgkolf** [comment]
I want to start working with that. Can you assign it on me? 
Cheers

**Comment by ghost** [comment]
Yes I can. All yours.
