### ISSUE TITLE
Dicas sobre a tela principal

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#22]
**Descrição da discussão:**
Dar dicas de melhorias da tela principal.

**Necessidade:**
A tela principal está muito simples, pois no inicio não sabia o que colocar lá, qual a melhor estrutura e etc. Pensei que poderia ser algo tipo o [OpenDevUFCG](https://opendevufcg.org), usando a ideia de separar por categorias.

**ATUALIZAÇÃO:**
Link para o figma: https://www.figma.com/file/57uLaXSbFV2izvOpYPpEkE/CamaraDosDeputados-Community . Para ser feito a criação da tela de home para então começar a implementação.

**Imagens:**
![image](https://user-images.githubusercontent.com/25726888/66263067-50b21d80-e7c3-11e9-9b67-657f2c89bc92.png)
![image](https://user-images.githubusercontent.com/25726888/66263072-60316680-e7c3-11e9-9a68-39b24ac6d24f.png)

**Comment by ghost** [comment]
E recomendo que deem uma olhada no que o [OpenDevUFCG](https://github.com/OpenDevUFCG) proporciona.

**Comment by Claudiney5** [comment]
O que vai na página inicial:
- qual o objetivo do App
- será necessário um cadastro?
- quais as informações que o App trará? Despesas, partido, projetos apresentados, votos dados, comissões que participa, cargo nessas comissões, etc.

Creio ser importante na tela inicial o usuário ter estas informações.

Uma boa imagem da câmara dos deputados  seria interessante também. Talvez não uma foto, mas o logo.

**Comment by ghost** [comment]
- Não será necessário um cadastro para visualizar as informações. Seria bom ter alguns ícones para compartilhar a página em redes sociais também. Talvez no header ?

- Essas informações que você citou todas podem ser utilizadas no site, meu objetivo é mostrar todas as informações disponíveis na API de uma forma de fácil visualização para o usuário. Seria bom uma página para cada informação dessa, um card com uma imagem e uma descrição, parecido com o que o site da API usa também(https://dadosabertos.camara.leg.br/index.html), acho que ficaria legal.

- A ideia da imagem é uma boa. Poderia ter essa imagem como background e o texto do objetivo do site por cima. Mas desconheço alguma imagem dessa, acha que só tem o logo.

Vou tentar achar um tempo e tentar fazer um projeto no figma para criação dessa tela, eu posso criar e disponibilizar aqui para quem quiser contribuir por lá também e quando estiver em boa fase ai já daria para implementar.

**Comment by ghost** [comment]
Fiz algumas coisas, um logo simples e uma estrutura inicial. Estou com dúvida em quais cores usar na aplicação.

Link para editarem no Figma: https://www.figma.com/file/57uLaXSbFV2izvOpYPpEkE/CamaraDosDeputados-Community

**Comment by ghost** [comment]
O @tuliocll fez um ótimo trabalho na issue #73 . Vou fechar essa e focar o trabalho nela.
