### ISSUE TITLE
Funcionalidade de buscar por um deputado

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#25]
**Descrição da feature:**
Na tela de listagem dos deputados teria um caixa de texto para realizar buscas pelo nome de um deputado.

**Necessidade:**
Facilitaria um usuário achar informações sobre determinado deputado.

**Implementação:**
Pode ser usado algumas bibliotecas do ReactJS. Tem algumas que facilitam a implementação dessa funcionalidade.

**Comment by igornfaustino** [comment]
eu posso fazer isso :)

**Comment by ghost** [comment]
Vou atribuir à você.
