### ISSUE TITLE
Funcionalidade de buscar por um partido

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#26]
**Descrição da feature:**
Na tela de listagem dos partidos teria um caixa de texto para realizar buscas pelo nome de um partido.

**Necessidade:**
Facilitaria um usuário achar informações sobre determinado partido.

**Implementação:**
Pode ser usado algumas bibliotecas do ReactJS. Tem algumas que facilitam a implementação dessa funcionalidade.

**Comment by igornfaustino** [comment]
enviado PR desta issue 😄

**Comment by ghost** [comment]
Obrigado mais uma vez!
