### ISSUE TITLE
Estilizar o input e button da tela de deputados

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#28]
**Descrição da feature:**
Estilizar a tela de deputados.

**Necessidade:**
Deixar um visual mais elegante para os usuários.

**Comment by marlonemmerich** [comment]
Olá, amigo! Posso fazer, caso queira

**Comment by ghost** [comment]
Pode sim, vou atribuir à você.

**Comment by marlonemmerich** [comment]
Olá! Só uma dúvida: você pretende usar alguma framework no front, como bootstrap ou materializecss ou seria css puro mesmo?
Um abraço!

**Comment by ghost** [comment]
Se você ver a necessidade pode utilizar. Mas como o projeto visa fazer com que a maior parte de pessoas contribuam, quanto mais simples o código, melhor.

**Comment by marlonemmerich** [comment]
Claro, entendo
Obrigado!

**Comment by yamitrvg12** [comment]
Hi @Rickecr 
Sorry to writing in english i don't speak Portuguese, Anyway i created a PR related to this issue:  

https://github.com/Rickecr/CamaraDosDeputados/pull/34

Please let me know what do you think about it

**Comment by ghost** [comment]
Eu te respondi com sugestões na PR que você abriu.

**Comment by ghost** [comment]
Vocês dois podem trabalhar na issue juntos caso queiram.

**Comment by marlonemmerich** [comment]
Acho que ele completou a tarefa já! Qualquer coisa só abrir uma nova issue que contribuo com o projeto ;)
