### ISSUE TITLE
Componente de "loading" nas telas de Deputados e Partidos

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#32]
**Descrição da feature:**
Adicionar um componente visual nas telas de `deputados` e `partidos` para dar um feedback ao usuário que as informações estão sendo carregadas.

**Necessidade:**
O usuário precisa saber que algo esta acontecendo no sistema e que não travou.

**Comment by Gutem** [comment]
Faço essa

**Comment by ghost** [comment]
Ok, vou atribuir à você.

**Comment by ghost** [comment]
@Gutem você pretende resolver esta issue ainda ?

**Status:** Issue aberta para novos Assigned.

**Comment by lucsrods** [comment]
Eu vejo
