### ISSUE TITLE
Tela de Partidos

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#38]
**Descrição do bug**
Na tela de partidos ao realizar uma busca acontece um BUG no CSS.

**Reproduzir o bug**
Etapas para reproduzir o bug:
1. Vá para página de partidos.
2. Realize a busca por um partido e clique em buscar.
3. Ver o erro.

**Comportamento esperado**
Deveria aparecer um `Card` normalmente, igual quando está vários.

**Imagens**
![image](https://user-images.githubusercontent.com/25726888/66363544-ffd62c80-e95c-11e9-9a46-89b6735cc1a9.png)

**Desktop (por favor, complete as seguintes informações):**
 - OS: Linux Mint
 - Browser: Google Chrome.

**Comment by tamirisapbonicenha** [comment]
Olá @Rickecr , eu posso pegar isso pra resolver. Tudo bem?

**Comment by ghost** [comment]
Pode sim, vou atribuir à você.

**Comment by ghost** [comment]
@tamirisapbonicenha, você ainda tem interesse em resolver a issue ?

**Comment by tamirisapbonicenha** [comment]
@Rickecr Desculpe pelo sumiço, tenho interesse sim, vou trabalhar nisso nesse domingo, tudo bem? ;)

**Comment by ghost** [comment]
Okay.

**Comment by tamirisapbonicenha** [comment]
#43 ;)

**Comment by ghost** [comment]
Vlw!
