### ISSUE TITLE
Estilizar tela de deputado

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#39]
**Descrição da feature:**
Estilizar/Dar ideias para a tela de deputado.

**Necessidade:**
A tela de deputado está bem simples, contento algumas informações, mas sem muita estilização.

**Implementação:**
Faça uso do framework CSS Bulma adicionado no projeto.

**Imagens:**
Você pode dar sugestões de páginas por meio de imagens.

**Comment by crisgon** [comment]
Olá, quero ajudar com essa tela.

**Comment by crisgon** [comment]
Tem algum guia de estilos(em relação as cores), que vocês estão seguindo?

**Comment by ghost** [comment]
Isso é uma boa ideia. Mas ainda não temos. Entretanto podemos continuar com o que o @matheushf e @lchiba fizeram em PR anteriores.

**Comment by ghost** [comment]
@crisgon, você ainda tem interesse em resolver a issue ?

**Comment by crisgon** [comment]
Opa, acabei não conseguindo fazer. Mas posso fazer nesse FDS. Pode ser?

**Comment by ghost** [comment]
Pode sim
