### ISSUE TITLE
Como que faz para pegar a sigla do sexo dos deputados ? 

### ISSUE THREAD

**Issue by viniciusbds** [Rickecr/CamaraDosDeputados#4]
Tentei ler o código da classe ApiCamara mas **não consegui encontrar uma forma de considerar o sexo de cada deputado**

Minha ideia era calcular a quantidade e a porcentagem de deputadas, que ,como é esperado, é muito menor que a de deputados 

    public String porcentagemDeDeputadas() {
		int mulheres = 0;
		for (Deputado deputado : deputados) {
			if (deputado.getSiglaSexo().equals("F")) {
				mulheres++;
			}
		}
		int porcentagem = (100 * mulheres) / deputados.size();
		return mulheres + " mulheres, " + porcentagem + "%";
	}
	
	public String porcentagemDeDeputados() {
		int homens = 0;
		for (Deputado deputado : deputados) {
			if (deputado.getSiglaSexo().equals("M")) {
				homens++;
			}
		}
		int porcentagem = (100 * homens) / deputados.size();
		return homens + " homens, " + porcentagem + "%";
	}

Na classe Deputado inseri:

    private String siglaSexo;

    public String getSiglaSexo() {
		return siglaSexo;
	}

	public void setSiglaSexo(String siglaSexo) {
		this.siglaSexo = siglaSexo;
	}

*A dúvida é: como inserir, nas instâncias de Deputado (enquanto os dados são lidos), as siglas dos sexos (F ou M) ?*

**Comment by Rickecr** [comment]
Para fazer isso pode consultar a [API](https://dadosabertos.camara.leg.br/swagger/api.html#api), que no [método](https://github.com/Rickecr/CamaraDosDeputados/blob/aef0aeffaa381e34431207e9144367d92bef653f/src/com/rick/services/ApiCamara.java#L34) ele recupera todos os deputados. E todos tem uma uri, que é o link para fazer outra requisição, e essa irá retorna um objeto deputado mais detalhado com essa informação do sexo, entre outros detalhes do deputado.

**Comment by Rickecr** [comment]
Portanto, na classe Deputado teria outros atributos e no [método](https://github.com/Rickecr/CamaraDosDeputados/blob/aef0aeffaa381e34431207e9144367d92bef653f/src/com/rick/services/ApiCamara.java#L34) não iriamos recuperar apenas o deputado básico, temos que fazer uma nova requisição usando a uri de cada deputado e adicionando em uma coleção, e então teríamos um melhor acesso aos deputados.

**Comment by Rickecr** [comment]
Concluído!
