### ISSUE TITLE
Estilizar tela de partido

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#40]
**Descrição da feature:**
Estilizar/Dar ideias para a tela de partido.

**Necessidade:**
A tela de partido está bem simples, contento algumas informações, mas sem muita estilização.

**Implementação:**
Faça uso do framework CSS Bulma adicionado no projeto.

**Imagens:**
Você pode dar sugestões de páginas por meio de imagens.

**Comment by karenngomes** [comment]
Olá! Posso usar uma UI framework também?

**Comment by ghost** [comment]
Caso esse que foi citado não resolva o problema, pode sim.

**Comment by ghost** [comment]
@jenicarvalho fez um ótimo trabalho! Vou deixar a issue aberta pois alguém pode ver alguma melhoria e enviar uma PR ou até mesmo criar uma issue.
