### ISSUE TITLE
Efeito hover nos botões da página de listagens de Deputados 

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#5]
**Descrição da feature:**
Colocar o efeito de hover nos botões.

**Necessidade:**
Para passar a melhor sensação que os botões são clicáveis.

**Implementação:**
No CSS, você pode adicionar a propriedade hover e mudar a opacidade do botão.

**Comment by lucascz37** [comment]
Posso fazer essa?

**Comment by ghost** [comment]
Pode sim.
