### ISSUE TITLE
Estilizar o componente de Despesas

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#52]
**Descrição da feature:**
Como diz no título.

**Necessidade:**
A implementação da listagem das despesas de cada deputado foi concluída. Entretanto, falta realizar uma estilização na componente.

**Implementação:**
Pode utilizar o Bulma, CSS framework, já esta instalado como uma dependência no projeto. Caso veja a necessidade de adicionar um novo framework fique a vontade para dar sua opinião.

Você pode mandar imagens de como acha que seria legal para nós avaliamos, caso queira.

**Comment by cesar-cb** [comment]
@Rickecr O que você acha de algo assim ? Tentei manter o padrão dos componentes da página

![image](https://user-images.githubusercontent.com/11877890/67637777-bbcfab00-f8bc-11e9-92d1-3c0c7f6b915c.png)

**Comment by ghost** [comment]
Ficou bem legal mesmo. Valeu!

Você desejar mandar a PR ?

**Comment by cesar-cb** [comment]
Sim, vou abrir uma PR
