### ISSUE TITLE
Loop infinito para dadosabertos api - pagina de detalhes do partido

### ISSUE THREAD

**Issue by tiagomatos8** [Rickecr/CamaraDosDeputados#56]
**Loop infinito de chamadas para dadosabertos api**
Linha 15 do arquivo src/Components/partidos/pagepartidos.js esta send chamada infinitamente mesmo depois da pagina estar totalmente renderizada.

**Reproduzir o bug**
Abra a aba de network do developer tools do seu browser.
Acesse: https://camaradeputados.herokuapp.com/partido/36814
Veja quantas chamadas sao feitas.

**Comportamento esperado**
Ter apenas uma chamada para api

**Comment by ghost** [comment]
Realmente. 
O `useEffect` está sem parâmetro nenhum. Acho que colocar `[]` como parâmetro deve resolver o problema.

E obrigado pela contribuição :star:

**Comment by ghost** [comment]
Corrigi este problema(#57). Agora ele faz apenas uma chamada para buscar as informações. Vou subir a versão que está aqui(Github) para o heroku, pois a do heroku já tá bem desatualizada em relação a que está em desenvolvimento.

Mais uma vez obrigado pela contribuição!
