### ISSUE TITLE
Algumas dicas para o projeto

### ISSUE THREAD

**Issue by felipe-heredia** [Rickecr/CamaraDosDeputados#59]
Olá, ainda estou analisando o projeto, mas de cara, já vejo uma coisa que poderia ser melhor.

O Heroku, é um sistema para hospedarmos sistemas em NodeJS. Para o nosso site em React, deveríamos utilizar o [Netlify](https://netlify.com).

**Comment by ghost** [comment]
Sim. Eu já tinha feito um deploy no netlify, no link: https://heuristic-mccarthy-38a85f.netlify.app/. Mas eu nem cheguei a trocar o link do heroku para esse link, só pq achei a URL do heroku mais bonitinha kkkk.

Ele faz o deploy sempre que uma PR é aceita. E também verifica se a PR não quebrou o deploy.

**Comment by felipe-heredia** [comment]
Olá, o Netlify também faz todos esses sistemas, você pode trocar o dominio com o nome que você quiser, vá em Site Setting > Change site name, daí é só escolher o nome que está disponível, assim mudará o nome do site [GatsbyCourse](https://curso-gatsby.netlify.app/ "Exemplo de Site"), este é através do Netlify, que é próprio para sites, e com sites pequenos, você pode ter sites ilimitados.

Não recomendo que utilize em seus projetos "O que for mais bonito", utilize a forma correta.

**Comment by felipe-heredia** [comment]
Vou fazer outro comentário a mais.

- __Utilize algo como Eslint ou Prettier para criar um padrão em seu código__, assim, se eu enviar um pull request, o código já estará formatado e você não precisará modifica-lo ou então fazer uma mistureba no código e ter diversos padrões.

**Comment by ghost** [comment]
Obrigado pelas sugestões. Vou fazer a configuração do Eslint e Prettier, realmente eles são bastantes úteis.

**Comment by ghost** [comment]
Adicionei o ESlint e o prettier no projeto! E Também fiz as alterações da hospedagem no netlify.

**Comment by felipe-heredia** [comment]
Vi suas modificações, lá vai algumas dicas para seus commits que aprendi esses dias:

1. Se o Commit tem mais de uma mudança (Por exemplo Adicionar Insomnioa.json e adicionar Prettier), crie dois commits.
2. As mensagens nos commits não são tão importantes, foque nos títulos, visto que isso que na página inicial do código aparecem os títulos e não as mensagens.
3. Você pode utilizar o [GitMoji](https://gitmoji.carloscuesta.me/ "Veja o site do Gitmoji") para deixar seus títulos de Commits melhores.

Estou trabalhando num [projeto](https://github.com/felipesuri/felipesuri-blog "Meu blog pessoal"), que é o meu blog pessoal, utilizando essas técnicas o resultado é muito bom, fica muito mais bonito e entendível.
