### ISSUE TITLE
Importa Insomnia.json

### ISSUE THREAD

**Issue by fariasmateuss** [Rickecr/CamaraDosDeputados#61]
**Descrição da feature:**
 Importa arquivo Insomnia.json para auxiliar a utilização API, visto a ausência da documentação.

**Necessidade:**
 Assim, ficará mais fácil  o entendimento das URL's, suas requisições e resposta para o frontend.

**Implementação:**
Adicionar para a pasta .github a importação.

**Comment by ghost** [comment]
Nunca utilizei isso. Poderia explicar mais detalhado o por que isso é necessário ?

Eu entendi que seria para detalhar a API, como usar, no caso a API da Câmara dos Deputados. Mas acho que a documentação dela é bem feita.
Link da documentação da API: https://dadosabertos.camara.leg.br/swagger/api.html

Seria isso ou eu entendi errado ?
