### ISSUE TITLE
Link pra API dos Dados Abertos quebrado.

### ISSUE THREAD

**Issue by leleoveiga** [Rickecr/CamaraDosDeputados#64]
**Descrição do bug**
O link referente a isso no README.md não leva a nada. Queria entender mais sobre essa api

**Comment by ghost** [comment]
Realmente estava com link incorreto. Corrigi lá já. Obrigado pelo aviso.

Link correto: https://dadosabertos.camara.leg.br/swagger/api.html

Tem algumas informações na página também, fala algumas coisas sobre os dados disponibilizados.

**Comment by leleoveiga** [comment]
> Realmente estava com link incorreto. Corrigi lá já. Obrigado pelo aviso.
> 
> Link correto: https://dadosabertos.camara.leg.br/swagger/api.html
> 
> Tem algumas informações na página também, fala algumas coisas sobre os dados disponibilizados.

vlw!
