### ISSUE TITLE
Trocar arquivos css para scss

### ISSUE THREAD

**Issue by tuliocll** [Rickecr/CamaraDosDeputados#69]
**Descrição da feature:**
Renomear arquivos css para arquivos scss para manter o padrão nos arquivos de estilos.

**Necessidade:**
Padronização do projeto.

**Implementação:**
Renomear e usar as variáveis caso necessário.

**Imagens:**

**Comment by victoriatrindade** [comment]
Posso pegar essa task? :)

**Comment by victoriatrindade** [comment]
Vou assumir essa task aqui amigos

**Comment by ghost** [comment]
Feito. Obrigado pelas contribuições!
