### ISSUE TITLE
Erro nas rotas do react router dom

### ISSUE THREAD

**Issue by tuliocll** [Rickecr/CamaraDosDeputados#71]
**Descrição do bug**
Quando copia e cola uma url (que não seja a home) o netlify da erro de rota não encontrada, por que o router dom processa as rotas do lado do cliente.

**Reproduzir o bug**
1. Etapas para reproduzir o bug:
2. Copie a url: https://camaradosdeputados.netlify.app/deputados/
3. Cole no navegador e dê enter
4. Ver o erro.

**Comportamento esperado**
O netlify precisa redirecionar todas a requisições para o index.html para que o router dom possa fazer o roteamento correto.

**Imagens**
![image (19)](https://user-images.githubusercontent.com/22357579/95147066-03f67f00-0756-11eb-91d9-788014963c9f.jpg)

**Desktop:**
 - OS: Arch Linux
 - Browser: Google Chrome
 - Versão: 85.0.4183.121

**Comment by ghost** [comment]
Feito!
