### ISSUE TITLE
Implementar tela de perfil de um Deputado

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#75]
**Descrição da feature:**
implementar a tela de perfil de um deputado. Já possui as informações na página, deve realizar as modificações no design da tela.

Link do figma: https://www.figma.com/file/d0EXcqtCoKIkeDIz5pBeGd/Prototype?node-id=0%3A1

**Necessidade:**
Para deixar o site mais atrativo.

**Implementação:**
Deve ser implementado usando scss.

**Imagens:**

![perfil_deputada](https://user-images.githubusercontent.com/25726888/95403973-24574280-08ea-11eb-87fb-dbe3de41fc94.PNG)

![page_deputado_2](https://user-images.githubusercontent.com/25726888/95404862-99c41280-08ec-11eb-9617-c9d0d1878c39.PNG)

**Comment by ghost** [comment]
Nessa segunda imagem deve apenas pegar a estilização dos botões de navegação(anterior, próxima)

**Comment by mathsantana** [comment]
Posso fazer essa issue?

**Comment by ghost** [comment]
Pode sim, vou te colocar como responsável.

**Comment by tuliocll** [comment]
Olá @mathsantana , nessa task tem dois componentes que eu já criei em um pr e você ira usar também, que é o componente de Tag e o de paginação, depois fazer um merge da master (quando o @richecr aceitar o pr #85 ) para pega-los!

**Comment by ghost** [comment]
Olá @tuliocll @mathsantana, vou dar uma olhada na tua PR ainda hoje @tuliocll , ai o @mathsantana faz o merge e usa os componentes

**Comment by ghost** [comment]
@mathsantana sua issue está livre para ser concluída, o @tuliocll fez as alterações nos componentes de paginação e tag(na PR #85). Tu pode fazer o merge da master e fazer as alterações. 

Qualquer dúvida só falar por aqui, que a gente tenta ajudar.
