### ISSUE TITLE
Implementar a tela Home(sem ranking)

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#83]
**Descrição da feature:**
implementar a tela home da aplicação. Sem a seção do ranking.

Link do figma: https://www.figma.com/file/d0EXcqtCoKIkeDIz5pBeGd/Prototype?node-id=0%3A1

**Necessidade:**
Para deixar o site mais atrativo visualmente.

**Implementação:**
Deve ser implementado usando scss.

**Imagens:**

![home_1](https://user-images.githubusercontent.com/25726888/96320559-1770d800-0fe9-11eb-9c9c-57f462f74512.png)
![home_2](https://user-images.githubusercontent.com/25726888/96320564-19d33200-0fe9-11eb-964d-368e344b321f.png)
![home_3](https://user-images.githubusercontent.com/25726888/96320567-1b045f00-0fe9-11eb-8433-376625d8567b.png)

**Comment by lucascz37** [comment]
Posso contribuir com essa issue?

**Comment by ghost** [comment]
Pode sim, te coloquei como responsável.
