### ISSUE TITLE
Mudar o cursor do mouse nos botões de `Próxima` e `Anterior` na tela de partidos

### ISSUE THREAD

**Issue by ghost** [Rickecr/CamaraDosDeputados#9]
**Descrição da feature:**
Mudar o cursor do mouse nos botões de `Próxima` e `Anterior`.

**Necessidade:**
Para passar a melhor sensação que os botões são clicáveis.

**Implementação:**
No CSS, você pode adicionar a propriedade `cursor` e mudar o cursor do mouse.

**Comment by hjJunior** [comment]
I'd like to work on it, can I?

**Comment by ghost** [comment]
yes you can, all yours.
